-- Підрахунок записів у кожній таблиці
SELECT 'CUSTOMER' as таблиця, COUNT(*) as записів FROM CUSTOMER
UNION ALL SELECT 'HALL', COUNT(*) FROM HALL
UNION ALL SELECT 'MOVIE', COUNT(*) FROM MOVIE
UNION ALL SELECT 'SEAT', COUNT(*) FROM SEAT
UNION ALL SELECT 'SESSION', COUNT(*) FROM SESSION
UNION ALL SELECT 'BOOKING', COUNT(*) FROM BOOKING
UNION ALL SELECT 'TICKET', COUNT(*) FROM TICKET;

-- Перегляд основних змін
SELECT '=== CUSTOMER ===' as info; SELECT * FROM CUSTOMER;
SELECT '=== MOVIE ===' as info; SELECT * FROM MOVIE;
SELECT '=== HALL ===' as info; SELECT * FROM HALL;
SELECT '=== SESSION ===' as info; SELECT * FROM SESSION;
SELECT '=== BOOKING ===' as info; SELECT * FROM BOOKING;
SELECT '=== TICKET ===' as info; SELECT * FROM TICKET;